### ISSUE TITLE
Enhancement Request - Add Diff checking for instance from instance

### ISSUE THREAD

**Issue by jacebenson** [macmorning/snowtools-webext#24]
Similar to how https://chrome.google.com/webstore/detail/swissnow-servicenow-toolb/jneeammdkdmlfgidcacmjmbijdmkdbjm has it working.

So when on a record, you can open a new tab diffing the content of the two.

**Comment by macmorning** [comment]
That's interesting. Need to think about how it would work, and how to fit it in the current UI schema.
Any thoughts?

**Comment by jacebenson** [comment]
Let me think about it.  How did SN do it for diffing records on upgrades?

**Comment by jacebenson** [comment]
https://community.servicenow.com/community?id=community_question&sys_id=df8707a9db1cdbc01dcaf3231f961947 looks like a script we can inject to just do it.

**Comment by macmorning** [comment]
Nice, I didn't know there was this DiffHelper script include. It's not client callable but there is a DiffAjax overlay that we can use.
Thoughts :
* The ajax call will have to be made from the background script with a fetch().
* So the browser action will have to send an event to the background script with the sys id of the object we are currently viewing, the source instance, and the target instance
* I don't think we can use the GlideBox seen in the example because we don't have access to the page Javascript execution environment, we need to create a custom dialog box. It could be tricky if we are limited by the size of the browser action. Maybe we could open a new tab to display the result instead ?

**Comment by jacebenson** [comment]
I've been trying to get this to work, and so far here's where I struggle.
I'd like to list a diff option for each 'known' instance, but the addon seems to error when i try something like this; https://github.com/jacebenson/snowtools-webext/blob/diff24/dialog/snowbelt.js#L491

**Comment by macmorning** [comment]
Nothing in the extension console when you open the browser action?
Also, did you try using the DiffAjax script include, rather than using an external lib?

**Comment by macmorning** [comment]
Hey Jace,
This is partially provided with the new "open on" feature that just lets you open the same object or list in a new tab on selected instance.
I'll close this one for now because it seems to complex to implement for this lightweight extension.
